### ISSUE TITLE
Avoid workflow get launched after commit in a loop !

### ISSUE THREAD

**Issue by tomtom94** [EndBug/add-and-commit#101]
**Describe the bug**
I am using `EndBug/add-and-commit@v5` but it launches a loop of Github Actions because, everytime there is a change the workflow get launched.

There is no support for that, and it looks like every body is gonna have the same issue.

**Workflow used**

```
name: Workflow branch master
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    name: Build and push image
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.REPO_TOKEN }}
      - name: Upgrade the version
        run: |
          VERSION=$(grep -oP '(?<=latest-)[0-9]+' ./.github/workflows/build-and-push-image-to-registry.yaml)
          OLD_VERSION=$VERSION
          NEW_VERSION=$(($VERSION + 1))
          sed -i "s/latest-$OLD_VERSION/latest-$NEW_VERSION/g" ./scaleway/values.yaml
          sed -i "s/latest-$OLD_VERSION/latest-$NEW_VERSION/g" ./.github/workflows/build-and-push-image-to-registry.yaml
      - name: Commit changes
        uses: EndBug/add-and-commit@v5
        with:
          message: "Robot version upgrade"
          add: "."
        env:
          GITHUB_TOKEN: ${{ secrets.REPO_TOKEN }}
```

**Expected behavior**
I wanna launch this workflow only if commit message is `Robot version upgrade`

**Comment by tomtom94** [comment]
Ok apparently you just need to use the if condition I am testing it not sure yet

```
      - name: Commit changes
        if: startsWith(github.event.head_commit.message, 'Robot') == true
        uses: EndBug/add-and-commit@v5
        with:
          message: "Robot version upgrade"
          add: "."
        env:
          GITHUB_TOKEN: ${{ secrets.REPO_TOKEN }}
```
