### ISSUE TITLE
Use $GITHUB_REF in commit message

### ISSUE THREAD

**Issue by mueller-ma** [EndBug/add-and-commit#123]
Hey,
I want to use this action as part of a release workflow of an app. I create a GitHub release with the new version name and the workflow copies this tag name to the source code, so it's shown in the about page of the app.
After that I want to commit this change:
````
     - name: Commit changes
        uses: EndBug/add-and-commit@v6
        with:
          add: '.'
          author_name: openhab-bot
          author_email: bot@openhab.org
          message: "Bump version to $GITHUB_REF and update fastlane metadata"
          signoff: true
          branch: master
          tag: "${GITHUB_REF}-fdroid"
          token: ${{ secrets.GITHUB_TOKEN }}
````

However the commit message is `Bump version to $GITHUB_REF and update fastlane metadata` and the new tag is called `${GITHUB_REF}-fdroid`. How can I source the variable `GITHUB_REF` in the message and tag name?
