### ISSUE TITLE
Commit with the environment variable.

### ISSUE THREAD

**Issue by benkim0414** [EndBug/add-and-commit#137]
Hello guys.
Thanks for making this nice GitHub action.
Is it possible to commit with a string of the environment variable?
I'd like to dynamically set the commit message.

Something like:
```
- name: Commit changes
  uses: EndBug/add-and-commit@v7
  with:
    author_name: author
    author_email: author@email.com
    message: ${{ env.COMMIT_MESSAGE }}
    add: 'packages/'
```
