### ISSUE TITLE
How to use variables in git add?

### ISSUE THREAD

**Issue by rugk** [EndBug/add-and-commit#141]
This did not work:
```
      - name: Add & Commit
        # You may pin to the exact commit or the version.
        # uses: EndBug/add-and-commit@b3c7c1e078a023d75fb0bd326e02962575ce0519
        uses: EndBug/add-and-commit@v7
        with:
          # Arguments for the git add command
          add: "$SCREENSHOT_DIR/" # optional, default is .
 ```

**Comment by EndBug** [comment]
Hi, you need to evaluate the string in the workflow itself, using [GitHub's context syntax](https://docs.github.com/en/actions/reference/context-and-expression-syntax-for-github-actions#contexts) (`${{ env.SCREENSHOT_DIR }}`).
If that is still undefined, please check that `SCREENSHOT_DIR` is defined as an environmental variable by logging it in a previous step, using:
```yaml
run: "echo $SCREENSHOT_DIR"
```

**Comment by rugk** [comment]
Ah okay this seems to work:
```
      - name: Add & Commit
        # You may pin to the exact commit or the version.
        # uses: EndBug/add-and-commit@b3c7c1e078a023d75fb0bd326e02962575ce0519
        uses: EndBug/add-and-commit@v7
        with:
          # Arguments for the git add command
          add: "${{ env.SCREENSHOT_DIR }}/" # optional, default is .
```
