### ISSUE TITLE
Username not found for Github

### ISSUE THREAD

**Issue by liechtym** [EndBug/add-and-commit#160]
Thanks for maintaining the awesome package!

We started using the `persist-credentials: false` flag when checking out the git repo. This fixed an issue we were having when installing a private repo. Since then, the action has been failing at the `add-and-commit` step with this error:

```Error: fatal: could not read Username for 'https://github.com': No such device or address```

Here is the code for our Github action: 

```
name: Lint source code
on: 
  push:
  pull_request:
    types: [opened]

jobs:
  run:
    name: Lint with ESLint
    runs-on: ubuntu-latest
    steps:

      - name: Checkout repo
        uses: actions/checkout@v2
        with:
          persist-credentials: false

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 15.x

      - name: Install dependencies
        run: npm install

      - name: Update source code
        run: npm run lint

      - name: Commit changes
        uses: EndBug/add-and-commit@v7
```
    
Here is the full output in the action for the add-and-commit step:
```
Add input parsed as single string, running 1 git add command.
> Using 'liechtym <liechtym@users.noreply.github.com>' as author.
> Using "Commit from GitHub Actions (Lint source code)" as commit message.
Internal logs
  > Staging files...
  > Adding files...
  > No files to remove.
  > Checking for uncommitted changes in the git working tree...
  > Found 47 changed files.
  Error: Error: fatal: could not read Username for 'https://github.com': No such device or address
  
Outputs
  committed: false
  pushed: false
  tagged: false
Error: Error: fatal: could not read Username for 'https://github.com': No such device or address
```

Any ideas of what might be the problem here / how we can fix it?

Thanks for you help.

**Comment by EndBug** [comment]
Hi, thanks for the issue! 
Just a quick question: the problem you were having with the private repo was happening in my action or it's just something else? Because if it's from this action then I'll also have to investigate that.

Anyway, your error is caused by the fact that my action uses the existing git user config, and now it's not valid since `actions/checkout` is no longer setting them for you. 
In order for the action to work properly, you'll have to configure your git credential yourself: that means that you either have to use an action that does that or you'll have to manually run the `git config` commands you need like this.

```yaml
- name: Set up GitHub credentials
  run: |
    git config ...
    ...
```

As you can see from [`actions/checkout`'s code](https://github.com/actions/checkout/blob/25a956c84d5dd820d28caab9f86b8d183aeeff3d/src/git-auth-helper.ts#L137), there's not a single way to configure your token, and so that's on you to decide what is best for your use case.
Anyway, it's way easier if you use `persist-credentials`, so make sure you really need to turn that off if you want to proceed.
(Of course, as I said, if the issue you mentioned at the beginning was caused y my action let me know so we can try to fix it ;))
