### ISSUE TITLE
Error: Repository not found

### ISSUE THREAD

**Issue by samrith-s** [EndBug/add-and-commit#186]
**Describe the bug**
When trying to commit, shows an error saying the repository is not found. 

Additional context: this is a private repository within the organization.

**Workflow used**
```yml
name: Types

on:
    push:
        branches:
            - dev

jobs:
    publish:
        name: 'Publish types'
        runs-on: ubuntu-latest
        permissions:
            contents: read
            packages: write
        env:
            working-directory: ./typings

        steps:
            - uses: actions/checkout@v2
              with:
                  fetch-depth: 5

            - uses: actions/setup-node@v2
              with:
                  node-version: 14.x
                  registry-url: https://npm.pkg.github.com/

            - name: Get cache path
              id: yarn-cache-dir-path
              run: echo "::set-output name=dir::$(yarn cache dir)"

            - name: Restore cache
              uses: actions/cache@v2
              id: yarn-cache # use this to check for `cache-hit` (`steps.yarn-cache.outputs.cache-hit != 'true'`)
              with:
                  path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
                  key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
                  restore-keys: |
                      ${{ runner.os }}-yarn-

            - name: Install dependencies
              run: yarn install --frozen-lockfile --ignore-scripts

            - name: Generate Prisma
              run: yarn prisma generate

            - name: Bump version
              run: |
                  yarn build
                  echo "PACKAGE_VERSION=$(cat package.json | grep \\\"version\\\" | head -1 | awk -F: '{ print $2 }' | sed 's/[\",]//g' | tr -d '[[:space:]]')" >> $GITHUB_ENV
              working-directory: ${{ env.working-directory }}

            - uses: EndBug/add-and-commit@v7
              name: 'Commit changes'
              with:
                  default_author: github_actions
                  message: 'chore(release): types@v${{ env.PACKAGE_VERSION }}'
                  tag: 'types@v${{ env.PACKAGE_VERSION }} --force'
                  push: true
              env:
                  GITHUB_TOKEN: ${{ github.token }}

            - run: npm publish
              working-directory: ${{ env.working-directory }}
              env:
                  NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

```

**Expected behavior**
It should commit and proceed to next step

**Logs**
Either provide a link to the action run or (if your repo is private) paste here the logs from the step that uses it. If you paste the logs, please use this template, and remember to paste the logs from all the different sections.
<details>
  <summary>Logs</summary>
<pre><code>
Run EndBug/add-and-commit@v7
  with:
    default_author: github_actions
    message: chore(release): types@v2021.4.26.8575
    tag: types@v2021.4.26.8575 --force
    push: true
    add: .
    cwd: .
    pull_strategy: --no-rebase
    github_token: ***
  env:
    working-directory: ./typings
    NPM_CONFIG_USERCONFIG: /home/runner/work/_temp/.npmrc
    NODE_AUTH_TOKEN: XXXXX-XXXXX-XXXXX-XXXXX
    PACKAGE_VERSION: 2021.4.26.8575
    GITHUB_TOKEN: ***
Running in /home/runner/work/core/core
Add input parsed as single string, running 1 git add command.
> Using 'github-actions <41898282+github-actions[bot]@users.noreply.github.com>' as author.
> Using "chore(release): types@v2021.4.26.8575" as commit message.
Internal logs
  > Staging files...
  > Adding files...
  > No files to remove.
  > Checking for uncommitted changes in the git working tree...
  > Found 1 changed files.
  {
    raw: '',
    remote: 'bridghq/core',
    branches: [ { name: 'main', tracking: 'origin/main' } ],
    tags: [ { name: 'v0.0.2-alpha.0', tracking: 'v0.0.2-alpha.0' } ]
  }
  > Switching/creating branch...
  M	typings/package.json
  Your branch is up to date with 'origin/dev'.
  
  > Pulling from remote...
  { raw: '', remote: null, branches: [], tags: [] }
  PullSummary {
    remoteMessages: RemoteMessageSummary { all: [] },
    created: [],
    deleted: [],
    files: [],
    deletions: {},
    insertions: {},
    summary: { changes: 0, deletions: 0, insertions: 0 }
  }
  > Re-staging files...
  > Creating commit...
  {
    author: null,
    branch: 'dev',
    commit: 'fecfd57',
    summary: { changes: 1, insertions: 2, deletions: 2 }
  }
  > Tagging commit...
  > Pushing commit to repo...
  Error: Error: Pushing to bridghq/core
  remote: Repository not found.
  fatal: repository 'bridghq/core' not found
  
Outputs
  committed: true
  pushed: false
  tagged: true
Error: Error: Pushing to bridghq/core
remote: Repository not found.
fatal: repository 'bridghq/core' not found
</code></pre>
</details>
