### ISSUE TITLE
Expected — Waiting for status to be reported after commit

### ISSUE THREAD

**Issue by aidan-melen** [EndBug/add-and-commit#188]
The objective of this workflow is to format the terraform source code and automatically commit these new changes to the branch.

> note the is simply a modification of the recommend [hashicorp workflow](https://github.com/hashicorp/setup-terraform)

```yaml
name: Terraform

on:
  push:
    branches:
      - main
  pull_request:

jobs:

  lint:
    name: Lint, Auto Format, and Validate
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 0.13.5
          cli_config_credentials_hostname: 'example.org'
          cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}

      - name: Init
        id: init
        run: terraform init

      - name: Format
        id: format
        run: terraform fmt --recursive
      
      - name: Add and Commit Auto Format Changes
        uses: EndBug/add-and-commit@v7
        with:
          author_name: '@${{ github.actor }}'
          message: 'Auto Format Terraform code changes.'
          add: '.'

      - name: Validate
        id: validate
        run: terraform validate
```

Problem: The initial commit with the badly formatted code triggers this `Lint, Auto Format, and Validate` to run. Which will format the code and commit to the branch like we want. However, this new commit fails to retrigger the `Lint, Auto Format, and Validate` a second time. As a result, the Require Checks in the branch protection rule gets stuck waiting for the job to re-trigger from the auto commit, but it never does. Instead you just get this

![Screen Shot 2021-05-05 at 3 21 36 PM](https://user-images.githubusercontent.com/54326778/117210928-97a83080-adb5-11eb-839f-80c3d940d30f.png)

Why is the job not re-triggering on the commit from this github action???
