### ISSUE TITLE
Output `sha` of committed changelog

### ISSUE THREAD

**Issue by CWSites** [EndBug/add-and-commit#200]
In my workflow I'm generating a changelog and using this action to commit the generated code back to my repo. After it's generated I'm creating a release in GitHub and publishing to NPM. Currently my workflow is using the original `sha` prior to this committing files back to my repo which is causing some issues.

What I'm looking for here is an output of the `sha` which includes the commit created by this action?

**Comment by EndBug** [comment]
Hi, this would be a nice addition to the already existing outputs!

In the meantime, here's a manual way to do it: you'll need to set up a step that outputs the current HEAD sha retrieved from git.
You can try something like this:

```yaml
# ...

- uses: EndBug/add-and-commit@v7
  # ...

- id: head_commit
  run: echo "::set-output name=commit_sha::$(git rev-parse HEAD)"
  shell: bash

- run: echo {{ steps.head_commit.outputs.commit_sha }}
```

Explanation:
- The step you set up needs to have a custom `id`, so that you can look it up later.
- To get the string containing the commit sha associated with `HEAD` (your latest commit), you need to use `git rev-parse HEAD` ([ref](https://stackoverflow.com/a/949391/7133466), [docs](https://git-scm.com/docs/git-rev-parse))
- In order to set an output using this value, you'll need to use a [workflow command](https://docs.github.com/en/actions/reference/workflow-commands-for-github-actions#setting-an-output-parameter)
- After setting the output, you can get its value in other steps by using an [expression](https://docs.github.com/en/actions/reference/context-and-expression-syntax-for-github-actions#about-contexts-and-expressions) that uses the [`steps` context](https://docs.github.com/en/actions/reference/context-and-expression-syntax-for-github-actions#steps-context)
