### ISSUE TITLE
[bug] Additional edge case for 'could not read Username'  (#146)

### ISSUE THREAD

**Issue by dmadisetti** [EndBug/add-and-commit#216]
**Describe the bug**
Same issue as #146 

**Workflow used**
```
      - name: checkout
        uses: actions/checkout@v2
        with:
          persist-credentials: false
```

**Expected behavior**
An understandable error as to why this occurred. Removing `persist-credentials: false` works, I just thought you'd like to know.

**Logs**
<details>
  <summary>Logs</summary>
<pre><code>Internal logs
  > Staging files...
  > Adding files...
  > No files to remove.
  > Checking for uncommitted changes in the git working tree...
  > Found 1 changed files.
  Error: Error: fatal: could not read Username for 'https://github.com': No such device or address
  
Outputs
  committed: false
  pushed: false
  tagged: false
Error: Error: fatal: could not read Username for 'https://github.com': No such device or address</code></pre>
</details>
