### ISSUE TITLE
Can't access github context in steps

### ISSUE THREAD

**Issue by PatrickAlphaC** [EndBug/add-and-commit#238]
I have a step that uses this package:
```yml
- name: Set Output
        id: get_updated
        run: echo "::set-output name=version::1.1.0"
- name: add and commit
        uses: EndBug/add-and-commit@v7
        with:
          default_author: github_actor
          message: 'Auto Update'
          push: true
          tag: ${{steps.get_updated.outputs.version}}
```
However the `tag` keeps showing up as blank, even when in a previous step I set the output.

I notice that the git commands don't go through a cli, but if that's true, how am I supposed to get variables for tag names?

**Comment by EndBug** [comment]
Hi, can you send me a link to an action run?

**Comment by PatrickAlphaC** [comment]
Ended up doing it here with a different package: https://github.com/smartcontractkit/chainlink-brownie-contracts/blob/main/.github/workflows/add-and-commit.yml

```
      - name: add and commit
        if: steps.check_outdated.outcome != 'success'
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          tagging_message: ${{steps.get_updated.outputs.version}}
          commit_message: ${{steps.get_updated.outputs.version}}
```

Here is an action that tried to use github context as a tag: 
https://github.com/smartcontractkit/chainlink-brownie-contracts/runs/3090716399?check_suite_focus=true
