### ISSUE TITLE
Support for commiter name

### ISSUE THREAD

**Issue by koppor** [EndBug/add-and-commit#263]
git distinguishes between author and committer (see https://stackoverflow.com/q/6755824/873282)

There is a GitHub actions user (`Author <actions@github.com>`) which leads to nice commits:

![grafik](https://user-images.githubusercontent.com/1366654/130014676-ebee0981-127f-4cf2-af13-7b323b04b838.png)

Would it be possible to support that in this action, too? Maybe as follows:

```yaml
    # The name of the user that will be displayed as the committer of the commit
    # Default: author_name
    comitter_name: Author

    # The email of the user that will be displayed as the author of the commit
    # Default: author_email
    comitter_email: actions@github.com
```
