### ISSUE TITLE
[Help Wanted] Could I pass a file to this Actions as commit messages?

### ISSUE THREAD

**Issue by Dragon1573** [EndBug/add-and-commit#300]
I'm currently using Scheduled GitHub Workflows (`.github/workflows/checkver.yaml`) for automatically update some "configuration files" (all stored in `bucket/` folder) of [my repository](https://github.com/Dragon1573/Scoop-Bucket) 6 hours once. There's a built-in `bin/checkver.ps1` Powershell script for the "configuration files" of that repository to automatically check for updates and refresh the contents. With my configuration, an `../update.log` file will be created outside the repository telling us what has been refreshed by the script.

```yaml
defaults:
  run:
    shell: pwsh -File {0}

jobs:
  update:
    runs-on: windows-latest
    steps:
      - name: Version Check
        run: |
          $env:PATH += ';C:\Scoop\shims'
          .\bin\checkver.ps1 -U *
          .\bin\checkver.ps1 -U * *> ..\update.log
      - name: Generate commit logs
        shell: bash
        run: |
          sed -i 'N;s/\n//g;s/^/- /g' ../update.log                # Format update log
          sed -i '1i Actions[bot]: Update Apps\n' ../update.log    # Append Subject line
```

I'm going to use contents of the `../update.log` file as commit message as if calling `git commit -F ../update.log` directly. BUT most of the time, those "configuration files" are "up to date" (contents of my configurations are fetched and automatically generated from another upstream, I don't know when they will update their configurations), causing an error and `git commit` exit with status code 1 instead of 0. The whole workflow will be failed all because of this unintended exit code.

Is there a way to use `../update.log` as commit message in this Actions? I really want this Action to help me handle this complex situation and decide if it needs to create a commit.

Thank you!

**Comment by EndBug** [comment]
I think you can use another action (like [`read-file`](https://github.com/marketplace/actions/read-file)) to read the file and save its contents to an output. You can then later get that output and use it as the commit message.

It would look like this:

```yaml
- uses: juliangruber/read-file-action@v1
  id: file
  with:
    path: ../update.log

- uses: EndBug/add-and-commit@v7
  with:
    message: "${{ steps.file.outputs.content }}"
```

Try using this and let me know if it works!
