### ISSUE TITLE
Tag creation does not trigger workflow waiting for new tags

### ISSUE THREAD

**Issue by FabrizioCafolla** [EndBug/add-and-commit#311]
**Describe the bug**
I am using add-and-commit action to create a commit and create a tag.The workflow works correctly, but the tag that is created does not trigger a second workflow that is listening when new tags are created. 

**Workflow used**
[Project](https://github.com/azionaventures/aziona-cli) with first workflow:
```   
      ...step change files...
      - name: Commit changes
        uses: EndBug/add-and-commit@v7
        with:
          author_name: ${{ github.event.inputs.author }}
          author_email: ${{ github.event.inputs.email }}
          message: 'Create version: ${{ github.event.inputs.version }}. Commit: ${{ github.sha }}'
          add: 'aziona/__init__.py'
          tag: 'v${{ github.event.inputs.version }} --force'
```
Second workflow trigged by new tag:

```   
on:
  push:
    branches:
      - "main"
    tags:
      - "v*.*.*"
```  

**Expected behavior**
I expect that by creating the tag through the action the second workflow will be activated (as happens if I create the tag manually)

**Logs**
(workflow logs)[https://github.com/azionaventures/aziona-cli/runs/3965189066?check_suite_focus=true]
