### ISSUE TITLE
Trouble with setting `push:` options

### ISSUE THREAD

**Issue by barrettj12** [EndBug/add-and-commit#320]
### Bug description
I am trying to set the options so that `git` will force push. Following the [README](../blob/master/README.md), I originally tried to set the following option in my config:
```yaml
push: origin ${branch input} --force --set-upstream
```
but this gave the following error:
```
error: src refspec ${branch does not match any
error: src refspec input} does not match any
```
From this, I figured that `${branch input}` was not supposed to be used literally in the command. From [this SO question](https://stackoverflow.com/a/58034787/152195600), I found out that `${GITHUB_REF##*/}` should return the current branch, so I tried changing it to:
```yaml
push: origin ${GITHUB_REF##*/} --force --set-upstream
```
However, this now makes it so that nothing at all is pushed:
```
  > Pushing commit to repo...
  
  {
    pushed: [],
    repo: '<my-repo>',
    remoteMessages: RemoteMessageSummary { all: [] }
  }
  > No tags to push.
```
while the log should look something like
```
  > Pushing commit to repo...
  
  {
    pushed: [],
    update: {
      head: { local: 'refs/heads/main', remote: 'refs/heads/main' },
      hash: { from: '<hash1>', to: '<hash2>' }
    },
    branch: { local: 'main', remote: 'main', remoteName: 'origin' },
    repo: '<my-repo>',
    ref: { local: 'refs/remotes/origin/main' },
    remoteMessages: RemoteMessageSummary { all: [] }
  }
  > No tags to push.
```

### Workflow used
```yaml
on: [push, pull_request]
jobs:
  make-pdf:
    runs-on: ubuntu-latest
    steps:
      - (... step that creates `main.pdf` file in CI env)
      - name: Upload PDF to repo
        uses: EndBug/add-and-commit@v7.4.0
        with:
          add: 'main.pdf'
          pull: 'NO-PULL'
#          push: origin ${GITHUB_REF##*/} --force --set-upstream
```

### Expected behavior
The `main.pdf` file would be added to the current branch in my repo.

**Comment by EndBug** [comment]
Oh ok, if you're pushing to the same branch that's checked out you can just set `push` to `--force`, without anything else, and that should work.

**Comment by AKJAW** [comment]
I was able to force push, using this set-up:
```yml
      - uses: EndBug/add-and-commit@v7
        name: Commit
        with:
          author_name: "GitHub Actions"
          author_email: "noreply@github.com"
          message: "Refresh versions.properties"
          branch: dependency-update
          push: "--force"
```
