### ISSUE TITLE
Branch cant be found

### ISSUE THREAD

**Issue by LRR1993** [EndBug/add-and-commit#335]
**Describe the bug**
using this action in a workflow to update the package json per pull request, but when running, it cant checkout the current branch used to trigger the action

**Workflow used**
```
on:
  pull_request_target:
    types: [labeled, opened, unlabeled, synchronize, reopened]
jobs:
  bump-package-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: copapow/version-bump-package@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          major_label: semver-major
          minor_label: semver-minor
          patch_label: semver-patch
          default_branch: main
      - run: |
          echo "Previous version: ${{ steps.bump.outputs.previous_version }}"
          echo "New Version: ${{ steps.bump.outputs.new_version }}"
      - uses: EndBug/add-and-commit@v7
        with:
          message: 'Bump package version'
          default_author: github_actions
```

**Expected behavior**
to push commit to remote branch

**Logs**
<details>
  <summary>Logs</summary>
<pre><code>Run EndBug/add-and-commit@v7

Running in #####
Add input parsed as single string, running 1 git add command.
> Using 'github-actions <41898282+github-actions[bot]@users.noreply.github.com>' as author.
> Using "Bump package version" as commit message.
> Running for a PR, the action will use 'feature/#101719-versioning' as ref.
Internal logs
  > Staging files...
  > Adding files...
  > No files to remove.
  > Checking for uncommitted changes in the git working tree...
  > Found 1 changed files.
  {
    raw: '',
    remote: '#####',
    branches: [
      {
        name: 'bug/#98589-asset-tree-not-unloading',
        tracking: 'origin/bug/#98589-asset-tree-not-unloading'
      },
      {
        name: 'bug/#99711-clicking-on-check-approve',
        tracking: 'origin/bug/#99711-clicking-on-check-approve'
      },
      {
        name: 'bug/#99711-disable-approved',
        tracking: 'origin/bug/#99711-disable-approved'
      },
      {
        name: 'dependabot/npm_and_yarn/cypress/code-coverage-3.9.12',
        tracking: 'origin/dependabot/npm_and_yarn/cypress/code-coverage-3.9.12'
      },
      {
        name: 'feature/#101069-api-call-error-handlers',
        tracking: 'origin/feature/#101069-api-call-error-handlers'
      },
      {
        name: 'feature/#101719-versioning',
        tracking: 'origin/feature/#101719-versioning'
      },
      {
        name: 'feature/#95973-cancel-token',
        tracking: 'origin/feature/#95973-cancel-token'
      },
      {
        name: 'feature/#97077-E2E-Testing-for-parameter-page',
        tracking: 'origin/feature/#97077-E2E-Testing-for-parameter-page'
      },
      {
        name: 'feature/#97960-param-wizard-refactor',
        tracking: 'origin/feature/#97960-param-wizard-refactor'
      },
      {
        name: 'feature/#99831-admin-post-permissions',
        tracking: 'origin/feature/#99831-admin-post-permissions'
      },
      { name: 'feature/docs', tracking: 'origin/feature/docs' },
      { name: 'feature/docs-2', tracking: 'origin/feature/docs-2' }
    ],
    tags: []
  }
  > Switching/creating branch...
Outputs
  committed: false
  commit_sha: undefined
  pushed: false
  tagged: false
Error: 'feature/#101719-versioning' branch not found.</code></pre>
</details>
