### ISSUE TITLE
Add `long_sha` output

### ISSUE THREAD

**Issue by EndBug** [EndBug/add-and-commit#341]
Hey @EndBug I appreciate your work here, would you be able to extend the sha output to be the full sha and not just the last 7 characters? I'm trying to use this on other actions which require the full sha.

_Originally posted by @CWSites in https://github.com/EndBug/add-and-commit/issues/200#issuecomment-996838708_

**Comment by EndBug** [comment]
@CWSites it sure is something that I could add!

In the meanwhile, you can get the full sha with `git rev-parse`. Here's a sample step you can use:

```yaml
- uses: EndBug/add-and-commit@...
  id: commit
  ...

- id: helper
  run: echo "::set-output name={long_sha}::{$(git rev-parse ${{ steps.commit.outputs.commit_sha }})}"

- name: Your other step
  run: echo ${{ steps.helper.outputs.long_sha }}
```

If I didn't make any typos, this should be a workaround: the `helper` step sets a `long_sha` output with the result of the `git rev-parse` command, that you can later use as an input.

**Comment by CWSites** [comment]
Thanks for the quick response, I'm testing this out now.

**Comment by CWSites** [comment]
I must be doing something wrong here, I'm getting back `0`. I'm generating a changelog then trying to commit the updated file. Here is my config.

```
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Generate Changelog
        uses: fabernovel/github-changelog-generator-action@master
        with:
          # https://github.com/github-changelog-generator/github-changelog-generator/wiki/Advanced-change-log-generation-examples#additional-options
          options: --token ${{ secrets.GITHUB_TOKEN }} --date-format %m/%d/%Y --output CHANGE_LOG.md --enhancement-label **Features:** --enhancement-labels enhancement --bug-labels defect --exclude-labels documentation,question,release --breaking-labels BREAKING-CHANGE --since-tag 1.0.0 --unreleased-label Current Release

      # https://github.com/marketplace/actions/add-commit
      - name: Commit and Push Changelog
        uses: EndBug/add-and-commit@v7.4.0
        with:
          add: CHANGE_LOG.md
          default_author: github_actions
          message: 'Update Changelog'

      - name: Generate Changelog SHA
        id: changelog-sha
        run: echo "::set-output name={long_sha}::{$(git rev-parse ${{ steps.commit.outputs.commit_sha }})}"

      - name: Print Changelog SHA
        run: echo ${{ steps.changelog-sha.outputs.long_sha }}
```

The output that I'm getting in my action is 
![Screen Shot 2021-12-17 at 3 06 38 PM](https://user-images.githubusercontent.com/1242102/146601736-a94b9b3d-2484-4300-b613-c99196dfa079.png)

**Comment by EndBug** [comment]
You forgot to add `id: commit` to the `add-and-commit` step

**Comment by CWSites** [comment]
Ohhh I see, thank you! Trying this now

**Comment by CWSites** [comment]
Alrighty, we are getting closer... 

```
      - name: Commit and Push Changelog
        id: commit
        uses: EndBug/add-and-commit@v7.4.0
        with:
          add: CHANGE_LOG.md
          default_author: github_actions
          message: 'Update Changelog'

      - name: Generate Changelog SHA
        id: changelog-sha
        run: echo "::set-output name={long_sha}::{$(git rev-parse ${{ steps.commit.outputs.commit_sha }})}"

      - name: Print Changelog SHA
        run: echo ${{ steps.changelog-sha.outputs.long_sha }}
```

The first part is showing the short SHA, the long output is still showing `{0}` though.

<img width="692" alt="Screen Shot 2021-12-17 at 8 31 35 PM" src="https://user-images.githubusercontent.com/1242102/146624547-b5dd24ca-7591-4d2b-8100-c16f12608e1e.png">

**Comment by EndBug** [comment]
Maybe it's the `-` in the id name (?)

**Comment by CWSites** [comment]
No joy, same output as above with `{0}`
```
      - name: Commit and Push Changelog
        id: commit
        uses: EndBug/add-and-commit@v7.4.0
        with:
          add: CHANGE_LOG.md
          default_author: github_actions
          message: 'Update Changelog'

      - name: Generate Changelog SHA
        id: generate_sha
        run: echo "::set-output name={long_sha}::{$(git rev-parse ${{ steps.commit.outputs.commit_sha }})}"

      - name: Print Changelog SHA
        run: echo ${{ steps.generate_sha.outputs.long_sha }}
```
