### ISSUE TITLE
Files added but not committed

### ISSUE THREAD

**Issue by secondmanveran** [EndBug/add-and-commit#346]
The first job of my workflow compiles Laravel assets, then sends them up to an artifact.

The next job, called create, creates a new release branch, checks out the branch, then pulls down the artifact files and applies them to the branch, then attempts to commit them using your action.

This create job looks like so:

```yml
create:
  name: Create and Commit
  needs: [compile]
  runs-on: ubuntu-latest

  steps:
    - name: Create Stage-Release Branch
      uses: peterjgrainger/action-create-branch@v2.0.1
      env:
        GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
      with:
        branch: 'stage-release'

    - name: Checkout
      uses: actions/checkout@v2
      with:
        ref: stage-release
        token: ${{ secrets.GH_TOKEN }}

    - name: Add artifact to branch
      uses: actions/download-artifact@v2
      with:
        name: assets
        path: public

    - name: Commit assets to branch
      uses: EndBug/add-and-commit@v7
      with:
        default_author: github_actor
        branch: stage-release
        message: 'chore(deploy): deploy development to stage'
        add: '.'
        pull: 'NO-PULL'
        push: true
```

The output of the job is this:

```
Running in /home/runner/work/builder/builder
Add input parsed as single string, running 1 git add command.
> Using 'secondmanveran <secondmanveran@users.noreply.github.com>' as author.
> Using "chore(deploy): deploy development to stage" as commit message.
Internal logs
  > Staging files...
  > Adding files...
  > No files to remove.
  > Checking for uncommitted changes in the git working tree...
> Working tree clean. Nothing to commit.
Outputs
  committed: false
  commit_sha: undefined
  pushed: false
  tagged: false
```

Is there some trick to get the action to pick up the staged files or what am I doing wrong?

Thanks

**Comment by EndBug** [comment]
It's weird, git should pick up any file changes...
Try to check whether the previous steps actually download the new files
Also, why are you creating the branch before checking out the repo with actions/checkout? Shouldn't it be the other way around?

**Comment by EndBug** [comment]
You could also try using a more specific path with the `--force` option, but it's just a guess

**Comment by secondmanveran** [comment]
I don't understand your question. You don't checkout repositories, you checkout branches. The action already lives inside of the repository.

The release branch is created based on the branch that is being accessed, in this case develop, we create a new branch from develop, then checkout that branch, add the artifact assets. 

The problem turned out to be that I was trying to push to a branch I was already working in ... duh ... all I needed to do was commit the changed files. 

I did end up using `-f public/` to add the files and that worked like a charm.

Anyway thanks for the great package.

**Comment by EndBug** [comment]
Glad to hear you solved it 👍🏻

**Comment by secondmanveran** [comment]
Hey, I'm still having issues with this, so apparently I'm doing something wrong.

I changed up the workflow some to eliminate the artifact, but I'm still not getting the files created by running my npm build to get committed to the branch.

Here are the steps I need to happen:

1. Create a new branch (staging) from the `develop` branch that was just pushed to. 
2. Build my Laravel app from the develop branch that was pushed to.
3. Compile js and css by running `npm build prod` (which will create assets in the public dir in the runner.
4. Commit that changed public directory to the `staging` branch created earlier.
5. Deploy the `staging` branch to Laravel Forge using the action created for that.
6. Once completed, delete the `staging` branch.

Here's my current `develop.yml` workflow:

```yml
name: Build Dev & Deploy

on:
  push:
    branches:
      - develop

  workflow_dispatch:

jobs:
  create:
    name: Create Branch
    runs-on: ubuntu-latest

    steps:
      - name: Create staging branch
        uses: peterjgrainger/action-create-branch@v2.1.0
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        with:
          branch: staging
          sha: ${{ github.sha }}

  compile:
    name: Craft Builder App
    needs: [create]
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: staging
          token: ${{ secrets.GH_TOKEN }}

      - name: Generate .env file
        run: echo "${{ secrets.STAGE_ENV }}" > .env

        # Set .env and directory permissions
      - run: sudo chown -R $(id -u):$(id -g) .env
      - run: chmod -R 777 storage bootstrap/cache

      - name: Install composer dependencies
        uses: shivammathur/setup-php@master
        with:
          php-version: '8.0'

        run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist

      - name: Install node and npm
        uses: actions/setup-node@v2
        with:
          node-version: 'lts/*'

      - run: npm install
      - run: php artisan ziggy:generate
      - run: npm run prod

      - name: Commit assets to branch
        uses: EndBug/add-and-commit@v7
        with:
          default_author: github_actor
          branch: staging
          message: 'chore(deploy): deploy develop code to stage'
          add: '-f public/'
          pull: 'NO-PULL'
          push: false

  deploy:
    name: Deploy to Laravel Forge
    needs: [compile, create]
    runs-on: ubuntu-latest

    steps:
      - name: Deploy
        uses: jbrooksuk/laravel-forge-action@v1.0.2
        with:
          api_key: ${{ secrets.FORGE_DEPLOY }}
          server_id: ${{ secrets.STAGE_SERVER_ID }}
          site_id: ${{ secrets.STAGE_SITE_ID }}

  remove:
    name: Remove staging branch
    needs: [deploy, create, compile]
    runs-on: ubuntu-latest

    steps:
      - name: Delete branch
        uses: dawidd6/action-delete-branch@v3
        with:
          github_token: ${{ secrets.GH_TOKEN }}
          branches: staging
```

This runs and completes without error, but my staging server does not end up with any of the compiled js and css assets after it's deployed.

I'm missing a step, or doing something wrong in your action that's stopping the process from saving correctly.

I'd appreciate you taking a look and letting me know what I'm missing.

I'll continue to make adjustments and will update if I resolve it.

Thanks.
