### ISSUE TITLE
Error after updating to 8.0.0: 'NO-PULL' does not appear to be a git repository

### ISSUE THREAD

**Issue by eygraber** [EndBug/add-and-commit#353]
After updating to v8.0.0 I removed the `branch: 'master'` input, and used `actions/checkout` to checkout `master` instead. Here's my config:

```
      - uses: actions/checkout@v2.4.0
        with:
          ref: 'master'
          token: ${{ secrets.PUSH_PAT }}

      - name: Prepare next dev version
        id: prepare_next_dev
        run: sed -i -e 's/${{ env.CURRENT_VERSION }}/${{ env.NEXT_VERSION }}/g' gradle.properties

      - name: Commit next dev version
        id: commit_next_dev
        uses: EndBug/add-and-commit@v8
        with:
          add: 'gradle.properties'
          default_author: github_actions
          message: "Prepare next dev version"
          pull: "NO-PULL"
```

<details>
  <summary>Logs</summary>
<pre><code>
Add input parsed as single string, running 1 git add command.
> Using 'github-actions <41898282+github-actions[bot]@users.noreply.github.com>' as author.
> Using "Prepare next dev version" as commit message.
Internal logs
  > Staging files...
  > Adding files...
  > No files to remove.
  > Checking for uncommitted changes in the git working tree...
  > Found 1 changed files.
  {
    raw: '',
    remote: 'https://github.com/***/android-date-time-input',
    branches: [ { name: 'time-input', tracking: 'origin/time-input' } ],
    tags: [
      { name: '0.9.0', tracking: '0.9.0' },
      { name: '0.9.1', tracking: '0.9.1' },
      { name: '0.9.2', tracking: '0.9.2' },
      { name: '0.9.3', tracking: '0.9.3' },
      { name: '0.9.4', tracking: '0.9.4' },
      { name: '0.9.5', tracking: '0.9.5' },
      { name: '0.9.6', tracking: '0.9.6' },
      { name: '0.9.7', tracking: '0.9.7' }
    ]
  }
  > Pulling from remote...
  { raw: '', remote: null, branches: [], tags: [] }
  Error: Error: fatal: 'NO-PULL' does not appear to be a git repository
  fatal: Could not read from remote repository.
  
  Please make sure you have the correct access rights
  and the repository exists.
</code></pre>
</details>
