### ISSUE TITLE
persist-credentials: false on actions/checkout causes EndBug/add-and-commit action to fail

### ISSUE THREAD

**Issue by cormacmccarthy** [EndBug/add-and-commit#385]
**Describe the bug**
I have to use `persist-credentials: false` because I am installing a private repo as an npm dependency before I run my build, so when I then call add-and-commit it fails with `fatal: could not read Username for 'https://github.com/': No such device or address`

**Workflow used**
(note I've anonymized my repo name by using the word "private" here)
```
            - name: Checkout repository
              uses: actions/checkout@main
              with:
                  persist-credentials: false
            - name: Install private dependency
              run: |
                  yarn add @private@git+https://${{ secrets.YARN_INSTALL_TOKEN }}@github.com/private/private.git
                  yarn install
            - name: Run Build
              run: yarn build
            - name: Commit build (for ghpages)
              uses: EndBug/add-and-commit@v4
              with:
                  add: src docs
                  force: true
                  message: Commits formatting to src/ and build to docs/
              env:
                  GITHUB_TOKEN: $
```

**Expected behavior**
I expect it to add and commit instead of failing

**Logs**
Either provide a link to the action run or (if your repo is private) paste here the logs from the step that uses it. If you paste the logs, please use this template, and remember to paste the logs from all the different sections.
<details>
  <summary>Logs</summary>
<pre><code>Run EndBug/add-and-commit@v4
  with:
    add: src docs
    force: true
    message: Commits formatting to src/ and build to docs/
    cwd: .
    signoff: false
  env:
    GITHUB_TOKEN: $
Using 'Christopher McCulloh <cmcculloh@salesforce.com>' as author.
Internal logs
  Running in /home/runner/work/svelte-labs-poc/svelte-labs-poc.
  Staging files...
  Checking for uncommitted changes in the git working tree...
  fatal: could not read Username for 'https://github.com': No such device or address
  Switching/creating branch...
  M	docs/components.html
  M	docs/components/Color.html
  M	docs/components/ContextToggle.html
  M	docs/components/Footer.html
  M	docs/components/Form.html
  M	docs/components/Header.html
  M	docs/components/Icon.html
  M	docs/components/NavItem.html
  M	docs/components/Section.html
  M	docs/fonts.html
  M	docs/import-test.html
  M	docs/index.html
  D	docs/internal/assets/Form.svelte_svelte_type_style_lang-a817fb3.css
  D	docs/internal/assets/pages/components/ContextToggle.svelte-122dd7a8.css
  A	docs/internal/assets/pages/components/ContextToggle.svelte-ec523381.css
  A	docs/internal/assets/pages/components/Form.svelte-37ae088.css
  A	docs/internal/chunks/index-cd0abce8.js
  D	docs/internal/chunks/index-e4064b.js
  D	docs/internal/error.svelte-002ccfe9.js
  A	docs/internal/error.svelte-cc6b0618.js
  A	docs/internal/layout.svelte-6dd1fd84.js
  D	docs/internal/layout.svelte-7461a0b.js
  M	docs/internal/manifest.json
  D	docs/internal/pages/components.svelte-59c8eeef.js
  A	docs/internal/pages/components.svelte-aba4f48a.js
  D	docs/internal/pages/components/Color.svelte-5dc93154.js
  A	docs/internal/pages/components/Color.svelte-b5d1dabd.js
  A	docs/internal/pages/components/ContextToggle.svelte-494f9459.js
  D	docs/internal/pages/components/ContextToggle.svelte-f26db863.js
  A	docs/internal/pages/components/Footer.svelte-765c0f1e.js
  D	docs/internal/pages/components/Footer.svelte-81dad8ca.js
  D	docs/internal/pages/components/Form.svelte-07fdbc2b.js
  A	docs/internal/pages/components/Form.svelte-1e93a509.js
  A	docs/internal/pages/components/Header.svelte-55706ba2.js
  D	docs/internal/pages/components/Header.svelte-e9daa049.js
  A	docs/internal/pages/components/Icon.svelte-82b85f22.js
  D	docs/internal/pages/components/Icon.svelte-8a54e798.js
  A	docs/internal/pages/components/NavItem.svelte-a5d2a189.js
  D	docs/internal/pages/components/NavItem.svelte-b1451bd1.js
  A	docs/internal/pages/components/Section.svelte-27d28593.js
  D	docs/internal/pages/components/Section.svelte-ad53aca9.js
  A	docs/internal/pages/fonts.svelte-7d277f.js
  D	docs/internal/pages/fonts.svelte-8dbbf0a8.js
  D	docs/internal/pages/import-test.svelte-4ef7950b.js
  A	docs/internal/pages/import-test.svelte-e0d6aa08.js
  A	docs/internal/pages/index.svelte-72e2bcec.js
  D	docs/internal/pages/index.svelte-b5c6606b.js
  A	docs/internal/start-14cddb42.js
  D	docs/internal/start-96da5b05.js
  M	docs/internal/version.json
  M	docs/screenshot-grey-box.png
  M	package.json
  M	yarn.lock
  Your branch is up to date with 'origin/master'.
  Pulling from remote...
  fatal: could not read Username for 'https://github.com': No such device or address
  Resetting files...
  Unstaged changes after reset:
  M	docs/components.html
  M	docs/components/Color.html
  M	docs/components/ContextToggle.html
  M	docs/components/Footer.html
  M	docs/components/Form.html
  M	docs/components/Header.html
  M	docs/components/Icon.html
  M	docs/components/NavItem.html
  M	docs/components/Section.html
  M	docs/fonts.html
  M	docs/import-test.html
  M	docs/index.html
  D	docs/internal/assets/Form.svelte_svelte_type_style_lang-a8173fb3.css
  D	docs/internal/assets/pages/components/ContextToggle.svelte-2dd7a8.css
  D	docs/internal/chunks/index-e456064b.js
  D	docs/internal/error.svelte-002ccfe9.js
  D	docs/internal/layout.svelte-77461a0b.js
  M	docs/internal/manifest.json
  D	docs/internal/pages/components.svelte-59c8eeef.js
  D	docs/internal/pages/components/Color.svelte-5dc93154.js
  D	docs/internal/pages/components/ContextToggle.svelte-f26db863.js
  D	docs/internal/pages/components/Footer.svelte-81dad8ca.js
  D	docs/internal/pages/components/Form.svelte-07fdbc2b.js
  D	docs/internal/pages/components/Header.svelte-e9daa049.js
  D	docs/internal/pages/components/Icon.svelte-8a54e798.js
  D	docs/internal/pages/components/NavItem.svelte-b51bd1.js
  D	docs/internal/pages/components/Section.svelte-ad53aca9.js
  D	docs/internal/pages/fonts.svelte-8dbbf0a8.js
  D	docs/internal/pages/import-test.svelte-4ef7950b.js
  D	docs/internal/pages/index.svelte-b5c6606b.js
  D	docs/internal/start-96da5b05.js
  M	docs/internal/version.json
  M	docs/screenshot-grey-box.png
  M	package.json
  M	yarn.lock
  Adding files...
  Removing files...
  Creating commit...
  [master e95078e] Commits formatting to src/ and build to docs/
   56 files changed, 248 insertions(+), 323 deletions(-)
   delete mode 100644 docs/internal/assets/pages/components/ContextToggle.svelte-122dd7a8.css
   create mode 100644 docs/internal/assets/pages/components/ContextToggle.svelte-ec523381.css
   rename docs/internal/assets/{Form.svelte_svelte_type_style_lang-a8173fb3.css => pages/components/Form.svelte-437ae088.css} (100%)
   rename docs/internal/chunks/{index-e456064b.js => index-cd0abce8.js} (98%)
   rename docs/internal/{error.svelte-002ccfe9.js => error.svelte-cc6b0618.js} (95%)
   rename docs/internal/{layout.svelte-77461a0b.js => layout.svelte-6dd1fd84.js} (88%)
   rename docs/internal/pages/{components.svelte-59c8eeef.js => components.svelte-aba4f48a.js} (57%)
   rename docs/internal/pages/components/{Color.svelte-5dc93154.js => Color.svelte-b5d1dabd.js} (70%)
   create mode 100644 docs/internal/pages/components/ContextToggle.svelte-494f9459.js
   delete mode 100644 docs/internal/pages/components/ContextToggle.svelte-f26db863.js
   rename docs/internal/pages/components/{Footer.svelte-81dad8ca.js => Footer.svelte-765c0f1e.js} (95%)
   delete mode 100644 docs/internal/pages/components/Form.svelte-07fdbc2b.js
   create mode 100644 docs/internal/pages/components/Form.svelte-1e93a509.js
   rename docs/internal/pages/components/{Header.svelte-e9daa049.js => Header.svelte-55706ba2.js} (94%)
   rename docs/internal/pages/components/{Icon.svelte-8a54e798.js => Icon.svelte-82b85f22.js} (66%)
   rename docs/internal/pages/components/{NavItem.svelte-b1451bd1.js => NavItem.svelte-a5d2a189.js} (65%)
   rename docs/internal/pages/components/{Section.svelte-ad53aca9.js => Section.svelte-27d28593.js} (96%)
   create mode 100644 docs/internal/pages/fonts.svelte-7d10277f.js
   delete mode 100644 docs/internal/pages/fonts.svelte-8dbbf0a8.js
   rename docs/internal/pages/{import-test.svelte-4ef7950b.js => import-test.svelte-e0d6aa08.js} (87%)
   create mode 100644 docs/internal/pages/index.svelte-72e2bcec.js
   delete mode 100644 docs/internal/pages/index.svelte-b5c6606b.js
   create mode 100644 docs/internal/start-14cddb42.js
   delete mode 100644 docs/internal/start-96da5b05.js
   rewrite docs/screenshot-grey-box.png (99%)
  Tagging commit...
  Pushing commits to repo...
  fatal: could not read Username for 'https://github.com/': No such device or address
  Pushing tags to repo...
  fatal: could not read Username for 'https://github.com/': No such device or address
Task completed..</code></pre>
</details>

**Comment by EndBug** [comment]
If you're using `persist-credentials: false` then you have to authenticate before running the action. Here's a way to do it: https://stackoverflow.com/a/18936804/7133466

**Comment by cormacmccarthy** [comment]
I did this and it is now working:

```
            - name: Checkout repository
              uses: actions/checkout@main
              with:
                  persist-credentials: false
            - name: Install private dependency
              run: |
                  yarn add @private@git+https://${{ secrets.PAT }}@github.com/private/private.git
                  yarn install
            - name: Run Build
              run: yarn build
            - name: Commit build (for ghpages)
              uses: EndBug/add-and-commit@v4
              with:
                  add: src docs
                  force: true
                  message: Commits formatting to src/ and build to docs/
              env:
                  GITHUB_TOKEN: ${{ secrets.PAT }}
```

Where `secrets.PAT` is a Github Personal Access Token that I named PAT.

Thanks!
