### ISSUE TITLE
Error: fatal: could not read Username for 'https://github.com': No such device or address

### ISSUE THREAD

**Issue by btjones-me** [EndBug/add-and-commit#410]
I've seen #160 and #281 but the solutions don't work. Our workflow works for runs <24h but anything that takes over 24h fails with the above. 

Error:

```
Run EndBug/add-and-commit@v7
Running in /***/.cml/cml-pbwz7jhvar/_work/ML_DefectDetector/ML_DefectDetector
Add input parsed as single string, running 1 git add command.
> Using '**** <****@users.noreply.github.com>' as author.
> Using "Training complete [skip ci]" as commit message.
Internal logs
Outputs
Error: Error: fatal: could not read Username for 'https://github.com/': No such device or address
```

Notes: The user quoted above `> Using '**** <****@users.noreply.github.com>' as author.` is not the same as the user who generated the PAT - should this be an issue? Any other ideas? 

Action:

```yaml
train:
    needs: deploy-cloud-runner
    runs-on: [self-hosted, cml-cpu]
    timeout-minutes: 4320 # 72h

    steps:

      - name: Checkout repo
        env:
          repo_token: ${{ secrets.SECRETNAMEREPLACED1 }}
        uses: actions/checkout@v2

      - name: Set up tool cache
        run: |
          export AGENT_TOOLSDIRECTORY=/opt/hostedtoolcache
          mkdir -p /opt/hostedtoolcache
          chmod 777 /opt/hostedtoolcache
          
      - name: Set up JPEG tools
        run: |
          sudo apt-get update
          sudo apt-get install --yes libturbojpeg libjpeg-progs exiftran
      - uses: actions/setup-node@v2
        with:
          node-version: '16'

      - uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - uses: iterative/setup-cml@v1
        with:
          sudo: false
          force: true

      - name: Sleep
        run: |
          sleep 25h
          echo DONE > dvc.lock
          
      - name: Commit updated dvc.lock
        env:
          repo_token: ${{ secrets.SECRETNAMEREPLACED1 }}
        uses: EndBug/add-and-commit@v7
        with:
          add: 'dvc.lock' # file to add to commit
          message: 'Training complete [skip ci]'
          push: true

```

**Comment by EndBug** [comment]
Well, the first thing that stands out to me is that you're setting a `repo-token` env variable for both `actions/checkout` and my action, but neither use it.
`actions/checkout@v2` has a `token` **_input_** you can use ([docs](https://github.com/actions/checkout/tree/v2#usage)), while my action doesn't need any token as it relies on the one already configured ([docs](https://github.com/EndBug/add-and-commit/tree/v7#tokens))

Try changing your step to this and let me know if it works:

```yaml
- name: Checkout repo
  with:
    token: ${{ secrets.SECRETNAMEREPLACED1 }}
  uses: actions/checkout@v2
```
