### ISSUE TITLE
Is there way to prevent the commit message from being overwritten?

### ISSUE THREAD

**Issue by airtonix** [EndBug/add-and-commit#428]
We have a step prior to `add-and-commit` that already performs a commit with a message we want to keep.

```yml
name: Process Changesets

description: |
  If any changsets are found in the .changeset/ directory - they'll be
  processed into CHANGELOGs and declared packages will have their
  version fields bumped.

runs:
  using: 'composite'

  steps:
    - name: Check for changesets
      shell: bash
      id: check-for-changesets
      run: echo "::set-output name=HasChangesets::$(pnpm run changeset -- status && echo 'true' || echo 'false')"

    - name: Process changesets
      if: steps.check-for-changesets.outputs.HasChangesets != 'false'
      shell: bash
      run: pnpm changeset -- version

    - name: 📜 Changesets created the following updates
      if: steps.check-for-changesets.outputs.HasChangesets != 'false'
      shell: bash
      run: git diff-tree --no-commit-id --name-only -r HEAD

    - name: 📲 Pulling any updates
      if: steps.check-for-changesets.outputs.HasChangesets != 'false'
      shell: bash
      run: git pull --no-edit origin ${{ github.ref_name }}

    - name: 🚚 Pushing new changes
      if: steps.check-for-changesets.outputs.HasChangesets != 'false'
      uses: EndBug/add-and-commit@v9

```

What's happening though is our commit history on `master` is having a default message from `add-and-commit` instead of the generated one from `@changesets/cli`: 

```
Commit from GitHub Actions (Mainline)
```

Prior to using `add-and-commit` the commit message looked like: 

```
RELEASING: Releasing N package(s) <rest of the commit body>
```
(where `N` is be a number)

Is there a way we can avoid clobbering the message?

**Comment by EndBug** [comment]
I'm not sure if I get this right, but you're using my action to create a second commit after `changesets` has already created one?

I guess you could get the commit message and set it as an output in a previous step, and then use it in the `message` input of my action.
Honestly, since it seems like you're only using the action to push to your repo, I think it would be easier for you to just push using a git command 😅

**Comment by airtonix** [comment]
i ended up doing this: 

```yml
name: Process Changesets

description: |
  If any changsets are found in the .changeset/ directory - they'll be
  processed into CHANGELOGs and declared packages will have their
  version fields bumped.

inputs:
  SkipCi:
    description: SkipCi
    required: false
    default: true
  UpdateLockfile:
    description: Should the action update the lockfile after bumping the versions?
    required: true
    default: false

runs:
  using: 'composite'

  steps:
    - name: Check for changesets
      shell: bash
      id: check-for-changesets
      run: echo "::set-output name=HasChangesets::$(pnpm run changeset -- status && echo 'true' || echo 'false')"

    - name: Process changesets
      if: steps.check-for-changesets.outputs.HasChangesets != 'false'
      shell: bash
      run: pnpm changeset -- version

    - name: 📜 Changesets created the following updates
      if: steps.check-for-changesets.outputs.HasChangesets != 'false'
      shell: bash
      run: git diff-tree --no-commit-id --name-only -r HEAD

    - name: 📲 Pulling any updates
      if: steps.check-for-changesets.outputs.HasChangesets != 'false'
      shell: bash
      run: git pull --no-edit origin ${{ github.ref_name }}

    - name: ♻️ Update lockfile
      if: steps.check-for-changesets.outputs.HasChangesets != 'false' && inputs.UpdateLockfile == 'true'
      shell: bash
      run: |
        pnpm i
        git add .

    - name: ✍️ Rewriting Commit
      if: steps.check-for-changesets.outputs.HasChangesets != 'false' && steps.check-for-changesets.outputs.SkipCi != 'true'
      shell: bash
      run: |
        MESSAGE_TITLE=$(git log -1 --pretty="%s")
        MESSAGE_BODY=$(git log -1 --pretty="%b" | sed -e 's/\[skip ci\]//')

        git commit --amend -m "${MESSAGE_TITLE}" -m "${MESSAGE_BODY}"

    - name: 🚚 Pushing new changes
      if: steps.check-for-changesets.outputs.HasChangesets != 'false'
      shell: bash
      run: git push

```
