### ISSUE TITLE
pushing a commit to the branch that the github action is ran on

### ISSUE THREAD

**Issue by callum-maguire** [EndBug/add-and-commit#430]
```
 - uses: EndBug/add-and-commit@v7.4.0
        with:
          add: 'something/frontend/src/locales/en/en.json'
          message: '[skip ci] Update translations from scanner'
          push: --force
```
This works but we want to run on the latest version

so we migrated to 
```
 - uses: EndBug/add-and-commit@v9.1.0
        with:
          add: 'something/frontend/src/locales/en/en.json'
          message: '[skip ci] Update translations from scanner'
          push: --force
```

This is not working, the error is `Error: fatal: You are not currently on a branch.`

Thank you for any help or assistance in advance

**Comment by EndBug** [comment]
Since v8.0.0, the action works with whatever has been checked out in previous steps ([changelog](https://github.com/EndBug/add-and-commit/blob/main/CHANGELOG.md#800---2022-01-20)).
If you check out the branch you want to push to with either git commands or `actions/checkout`, then the action will push to that branch.
You can also use the `pull` input to run git pull before creating the commit.

**Comment by anuj-scanova** [comment]
@callum-maguire I got it working with the following
```
      - name: Update pull request
        uses: EndBug/add-and-commit@v9
        with:
          author_name: i18n Extract
          committer_name: GitHub Actions
          committer_email: 41898282+github-actions[bot]@users.noreply.github.com
          add: '*.xlf'
          fetch: false
```

Hope this helps you too.
