### ISSUE TITLE
It doesn't commit changes in PRs when PR is coming from the forked repo 

### ISSUE THREAD

**Issue by abrardev99** [EndBug/add-and-commit#442]
**Describe the bug**
We are using the `php-cs-fixer` in GitHub actions to automatically push the corrected/linted code into PR. It's working fine but If the PR is created from a different repo, it doesn't push the changes and throws the error "Error: Error: There is no tracking information for the current branch.". 
<img width="565" alt="image" src="https://user-images.githubusercontent.com/54532330/195336512-588fb0e8-dd2a-435c-bb0a-96473c1c8ffe.png">

**Workflow used**
```yml
php-cs-fixer:
  name: Code style (php-cs-fixer)
  runs-on: ubuntu-latest
  steps:
    - uses: actions/checkout@v2
    - name: Install php-cs-fixer
      run: composer global require friendsofphp/php-cs-fixer
    - name: Run php-cs-fixer
      run: $HOME/.composer/vendor/bin/php-cs-fixer fix --config=.php-cs-fixer.php
    - name: Commit changes from php-cs-fixer
      uses: EndBug/add-and-commit@v5
      with:
        author_name: "PHP CS Fixer"
        author_email: "phpcsfixer@example.com"
        message: Fix code style (php-cs-fixer)
```

**Expected behavior**
It should commit changes back to the PR. 

**Logs**
Repo is public and you can see the failed action: https://github.com/archtechx/tenancy/actions/runs/3214226040/jobs/5254464565.
