### ISSUE TITLE
help please

### ISSUE THREAD

**Issue by MohammedAlrozzi** [EndBug/add-and-commit#446]
Hi everyone, I am a hobbyist. I've been trying to use the output - response of an exernal api (in GitHub action), but I would like to push this output to the repository. is this possible? the current workflow looks like this:
```yaml
name: post Toshl Me to slack
on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  test-curl-action:
    name: "Perform REST API- toshl"
    runs-on: ubuntu-latest
    steps:
      - name: "Call API -GET me"
        uses: indiesdev/curl@v1.1
        with:
          # The target URL
          # Required: true if custom-config is not set
          url: https://api.toshl.com/me

          # The request method, basically it's one of GET|POST|PUT|PATCH
          # Default is GET
          method: "GET"

          # List of response status codes to be accepted, else it will set the job to be failed
          # If more than one value is needed, you can use comma(,) as seperator
          # In this case if the response status code is not one of 200, 201 and 204, the job will be failed
          # Default is 200,201,204
          accept: 200,201,204

          # Headers can be passed through json object string
          #headers: '{ "custom-header": "value" }'

          # Params can be passed through json object string
          #params: '{ "param1": "value", "param2": "value2" }'

          # Body request
          # Apply only to POST|PUT request
          #body: '{ "name": "breeze",  "job": "devops" }'

          # Request timeout (millisec)
          # Default: 1000
          timeout: 1000

          # Basic authentication using username and password
          # This will override the Authorization header, for example Authorization: Basic QWxhZGRpbjpPcGVuU2VzYW1l
          # Format => username:password as base 64
          #basic-auth-token: ${{ secrets.curl_auth_token }}

          # The authentication using token
          # This will override the Authorization header, for example Authorization: Bearer QWxhZGRpbjpPcGVuU2VzYW1l
          bearer-token: ${{ secrets.bearer_token }}

          # If you want to use proxy with the request, you can use proxy-url
          # Format => host:port
          #proxy-url: https://proxy-url:3000

          # If the proxy host requires the authentication, you can use proxy-auth to pass credentials
          # Format => username:password as base64
          #proxy-auth-token: ${{ secrets.proxy_auth_token }}

          # If it is set to true, it will show the response log in the Github UI
          # Default: false
          log-response: true

          # Retries specify the number of retry attemps before giving up.
          # Default: 1
          retries: 3

          # If you want to use axios config directly, you can pass config file to the action
          # The file is just basically a json file that has the same format as axios config https://github.com/axios/axios#request-config
          # If this input is set, it will ignore other inputs that related to the config
          # The path file is start from root directory of the repo
          #custom-config: .github/workflows/curl-config.json
          #log-response: true
        id: the_results
```

Thanks so much.

**Comment by EndBug** [comment]
Sure, you can use the [`steps` context](https://docs.github.com/en/actions/learn-github-actions/contexts#steps-context) to get the output and save it in a file, then just commit that file!
For the action output, there's also an example on their README: https://github.com/indiesdev/curl#use-response

```yaml
# ...

      - name: Save output
        # echo "abc" > file is a way to save the output of the command to a file in unix shells
        run: echo ${{ steps.the_result.outputs.response }} > output.txt
      
      - name: Commit file
        uses: EndBug/add-and-commit@v9
        with:
          add: output.txt
```
