### ISSUE TITLE
EndBug/add-and-commit@v9 causes PR to never see that the action has completed. 

### ISSUE THREAD

**Issue by cathalmf** [EndBug/add-and-commit#447]
**Describe the bug**
When i use EndBug/add-and-commit@v9 to add a file during a PR action the PR never sees when the action completes. 
this is resolved by closing and reopening the PR. 
it seems the addition of a file breaks it somehow. 

**Workflow used**
```
name: PR-Script

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  contract-build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
    - uses: actions/checkout@v3
      with:
        repository: ${{ github.event.pull_request.head.repo.full_name }}
        ref: ${{ github.event.pull_request.head.ref }}
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm install @openzeppelin/contracts-upgradeable
    - run: npm install hardhat
    - run: npx hardhat compile
    - uses: EndBug/add-and-commit@v9
      with:
        message: 'Added file containing ABI and Bytecode'
        add: 'ContractFile.json --force'
        cwd: './artifacts/contracts/test-contract/ContractFile.sol/'
    
  hardhat-tests:
    needs: contract-build
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'

    - run: npm install @nomicfoundation/hardhat-toolbox
    - run: npm install @openzeppelin/contracts-upgradeable
    
    - run: npx hardhat test "test/script.js" 
    - run: npx hardhat coverage --testfiles "test/script.js"
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v3
      with:
        token: ${{ secrets.CODECOV }}
        directory: ./coverage/
        fail_ci_if_error: true
        flags: unittests
        name: codecov-umbrella
        verbose: true

```

**Expected behavior**
I expect the file to be added and the PR script to continue.
