### ISSUE TITLE
"Error: Error: Could not read from remote repository." with @v9

### ISSUE THREAD

**Issue by vitalyk-multinarity** [EndBug/add-and-commit#450]
**Describe the bug**
"Error: Error: Could not read from remote repository" error using @v9

The same flow works with v7.5.0

Note: with checkout@v3 I'm using PAT instead of default token.

Similar to https://github.com/EndBug/add-and-commit/issues/199
**Workflow used**
```
 - name: Update  plugins  
      uses: EndBug/add-and-commit@v9
      with:
        add: 'my_path'
        message: 'CI: Updating control-*.aar [skip ci]'
        pull: 'NO-PULL'    
```
**Expected behavior**
git add / git commit / git push

**Logs**
Either provide a link to the action run or (if your repo is private) paste here the logs from the step that uses it. If you paste the logs, please use this template, and remember to paste the logs from all the different sections.
<details>
  <summary>Logs</summary>
<pre><code>Run EndBug/add-and-commit@v9
  with:
    add: my-peth
    message: CI: Updating control*.aar [skip ci]
    pull: NO-PULL
    cwd: .
    default_author: github_actor
    fetch: --tags --force
    pathspec_error_handling: ignore
    push: true
    github_token: ***
  env:
    JAVA_HOME: /opt/hostedtoolcache/Java_Zulu_jdk/8.0.35[2](https://github.com/multinarity/SpaceTop-Unity/actions/runs/3361537012/jobs/5572055054#step:12:2)-8/x64
    JAVA_HOME_8_X64: /opt/hostedtoolcache/Java_Zulu_jdk/8.0.[3](https://github.com/multinarity/SpaceTop-Unity/actions/runs/3361537012/jobs/5572055054#step:12:3)52-8/x6[4](https://github.com/multinarity/SpaceTop-Unity/actions/runs/3361537012/jobs/5572055054#step:12:4)
Running in /home/runner/work/my-repo/my-repo
Add input parsed as single string, running 1 git add command.
> Using 'vitalyk<vitalyk@users.noreply.github.com>' as author.
> Using "CI: Updating control-*.aar [skip ci]" as commit message.
Internal logs
  > Staging files...
  > Adding files...
  > No files to remove.
  > Checking for uncommitted changes in the git working tree...
  > Found 2 changed files.
  > Fetching repo...
  { raw: '', remote: null, branches: [], tags: [] }
  > Pulling from remote...
  { raw: '', remote: null, branches: [], tags: [] }
  Error: Error: Could not read from remote repository.
Outputs
  committed: false
  commit_long_sha: undefined
  commit_sha: undefined
  pushed: false
  tagged: false
  tag_pushed: false
Error: Error: Could not read from remote repository.</code></pre>
</details>

**Comment by EndBug** [comment]
The info in this logs is not sufficient to determine the cause of the issue
Would you be able to provide some context on the previous steps?

**Comment by vitalyk-multinarity** [comment]
> The info in this logs is not sufficient to determine the cause of the issue Would you be able to provide some context on the previous steps?

Sure! In fact, there are no tricky things in my workflow - I run checkout, build,  copy a few files into the local repo, and want to update them into the remote repo.

```
- name: Checkout Sources
      uses: actions/checkout@v3
      with:
          lfs: true
          fetch-depth: '0'
          submodules: 'true'
          token: ${{ secrets.CI_TOKEN }}
```

**Comment by EndBug** [comment]
@vitalyk-multinarity What happens if you remove `fetch-depth` from the `actions/checkout` inputs? There are some users that reported weird behavior while using that argument.

**Comment by vitalyk-multinarity** [comment]
1) @EndBug - unfortunately that didn't help. There is no "couldn't read from remote repo" error, but instead of this I'm getting "fatal: remote error: upload-pack: not our ref xxxxxxx" for one of submodules
2) When I tried to replace add-and-commit with a plain shell, that works as follows:

```
        git config --global user.email "ci@example.com"
         git config --global user.name "CI GitHub"
         git add Assets/........./libs/
         git commit -m "CI: Updating control-*.aar [skip ci]"
         git push
```

**Comment by EndBug** [comment]
I think I figured it out ahahha
You've set `pull` to `NO-PULL`, while you should have just not used it. It can't pull because your repo has no "NO-PULL" ref!

I think that if you try using this it'll work:

```yaml
 - name: Update  plugins  
   uses: EndBug/add-and-commit@v9
   with:
     add: 'my_path'
     message: 'CI: Updating control-*.aar [skip ci]'
```
