### ISSUE TITLE
Is my workflow with this action supposed to run on push from action?

### ISSUE THREAD

**Issue by neergaard** [EndBug/add-and-commit#476]
Hi, I am new to using GitHub Actions, so I might be missing some essential info on how to set this up.

I am using `add-and-commit` to make a TeX to PDF conversion every time I update the repository. My workflow looks like this:

```yaml
name: TeX to PDF

on: push

jobs:
  convert_via_pandoc:
    runs-on: ubuntu-latest
    steps:
      - name: Pull everything
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GH_ACCESS_TOKEN }}
          
      - name: Convert to PDF
        uses: closoco/pdflatex-action@v1.0.0
        with:
          texFile: main.tex
          
      - name: Remove auxiliary files
        run: |
          rm *.aux
          rm *.log
          rm *.out
          
      - name: Push changes
        uses: EndBug/add-and-commit@v9 # You can change this to use a specific version.
        with:
          committer_name: GitHub Actions
          committer_email: actions@github.com
          add: '.'
          message: 'TeX to PDF conversion'
```

However, I noticed since I set it up yesterday, that I have almost 500 new commits to my repository, even though I haven't made any push changes to the TeX file.

I suspect it is because the workflow is triggered by the push action from `add-and-commit`, but is this really how it is supposed to be? I assume I am missing something here, but it doesn't seem right to me that the action should be triggered by itself.

Thanks!

**Comment by EndBug** [comment]
Hey 👋🏻 
So, the main issue is that you're using a PAT to checkout the repo: that means that the CI makes the commit as if it was really you, so when it gets pushed to the repo it triggers another workflow, and so on forever

You should just delete the `token` input from `actions/checkout`'s step:
```diff
       - name: Pull everything
         uses: actions/checkout@v3
-        with:
-          token: ${{ secrets.GH_ACCESS_TOKEN }}
```

**Comment by neergaard** [comment]
Hi @EndBug , thanks for replying so fast!

I originally also had written the workflow without the token, but then I kept getting these error messages about permissions:

![image](https://user-images.githubusercontent.com/10213572/216969694-1ecc2038-1646-431a-a9ce-42d06911e5b5.png)

So that's why I thought to include the token.

**Comment by EndBug** [comment]
Did set up any branch protection rules? Maybe it's because you the protection rules say that you can't directly push to the branch, but you can because you're an admin

If you don't want to change the branch protection rules, a workaround you can use is making the workflow run only when the source `.tex` files are changed:

```yaml
on:
  push:
    paths:
      - **.tex
```

I would also suggest you commit only `.pdf` files, so your workflow would end up looking like this:

```yaml
name: TeX to PDF

on:
  push:
    paths:
      - **.tex

jobs:
  convert_via_pandoc:
    runs-on: ubuntu-latest
    steps:
      - name: Pull everything
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GH_ACCESS_TOKEN }} # Keep only if necessary
          
      - name: Convert to PDF
        uses: closoco/pdflatex-action@v1.0.0
        with:
          texFile: main.tex
          
      - name: Push changes
        uses: EndBug/add-and-commit@v9
        with:
          committer_name: GitHub Actions
          committer_email: actions@github.com
          add: *.pdf
          message: 'TeX to PDF conversion'
