### ISSUE TITLE
Annotation from sibiraj-s/action-eslint@v2 removed when commiting

### ISSUE THREAD

**Issue by keironlowe-edriving** [EndBug/add-and-commit#486]
Hi, I don't know if this is an issue with this action or sibiraj-s/action-eslint@v2 but I've raised an [issue](https://github.com/sibiraj-s/action-eslint/issues/10) on there as well. 

I've got the following steps, and when I disable the commit step, I see the annotation correctly added but with the commit, no annotations are included. It only seems to happen if there are issues eslint can fix itself (therefore something has changed that can be commited) but not everything can be fixed.

Like I say I'm not sure where the issue lies, the annotations are added by the other action so I would think it's that action, but they're only removed when committing using this action.

```
- name: Run ESLint
  uses: sibiraj-s/action-eslint@v2
  with:
    eslint-args: '--fix'
    extensions: 'js,ts,tsx,html'
    annotations: true

- name: Commit changes
  uses: EndBug/add-and-commit@v9
  with:
    message: 'ESLint Fixes'
```
