### ISSUE TITLE
Remove breaks when used with pull

### ISSUE THREAD

**Issue by krokofant** [EndBug/add-and-commit#492]
Consider this:
```yaml
- uses: EndBug/add-and-commit@v9
  with:
    add: '["file-that-changed.txt"]'
    remove: '["file-that-was-removed.txt"]'
    author_name: GitHub-Automated
    author_email: foo@example.com
    default_author: github_actor
    message: "Changing files"
    pathspec_error_handling: exitImmediately
    pull: "--rebase --autostash"
    push: false
```

First the file is removed [here](https://github.com/EndBug/add-and-commit/blob/68833114252f522ff708a3c59686e7baf53c4d5e/src/main.ts#LL29C31-L29C31)

Then if `pull` is used, the file is also removed [here](https://github.com/EndBug/add-and-commit/blob/68833114252f522ff708a3c59686e7baf53c4d5e/src/main.ts#L107) which breaks the action, since the file is already marked as removed.
> ::error::Error: fatal: pathspec 'file-that-was-removed.txt' did not match any files
> ::error::Error: Remove command did not match any file:%0A  git rm file-that-was-removed.txt
