### ISSUE TITLE
How to get push working when another commit was pushed?

### ISSUE THREAD

**Issue by louisabraham** [EndBug/add-and-commit#499]
When pushing two commits in close succession, the first task doesn't want to push because there are new commits.

Therefore I trid to pull. I tried various methods but I always get 

```
 > Pulling from remote...
  { raw: '', remote: null, branches: [], tags: [] }
    Error: Error: Could not read from remote repository.
  ```

I have no problem pushing when the commits are rare so I think the access is well configured.

Here is my actions:

```
      - name: Upload pdf
        uses: EndBug/add-and-commit@v9
        with:
          add: paper/article.pdf
          message: 'Update pdf'
          author_name: ${{ github.actor }}
          author_email: ${{ github.actor }}@users.noreply.github.com
```
