### ISSUE TITLE
Can't find commit when triggering on release publish

### ISSUE THREAD

**Issue by williamscs** [EndBug/add-and-commit#51]
When working on a pipeline that is triggered by a release publish:
```
on:
  release:
    types: [ published ]
```

I get the following error:
```
Unable to get commit from workflow event: trying with the GitHub API...
Error: Request failed with status code 404
    at createError (/home/runner/work/_actions/EndBug/add-and-commit/v4.4.0/lib/index.js:1:428)
    at settle (/home/runner/work/_actions/EndBug/add-and-commit/v4.4.0/lib/index.js:1:31578)
```

It seems like the latest changes have broken this functionality. I pinned the library to v4.3.0 and was able to run successfully.

**Comment by EndBug** [comment]
Hi, thanks for the report, I'll add a proper catch statement to fix this.

It's really weird though since that part of the code should not result in a 404 error: can I see the whole step or workflow? Also, is this running on a public or on a private repo?

**Comment by williamscs** [comment]
This is a private repo.

The steps are just incrementing the version:
```
      - name: Increment package version
        run: npm --no-git-tag-version version minor

      - name: Commit changes
        uses: EndBug/add-and-commit@v4.3.0
        with:
          message: "Increment minor version"
          add: "*.json"

      - name: Push changes
        uses: ad-m/github-push-action@v0.5.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
```
