### ISSUE TITLE
Pre-Commit script

### ISSUE THREAD

**Issue by BioPhoton** [EndBug/add-and-commit#514]
Is it possible to add a pre-commit script?
This could improve the DX of the action an shrinks code.

**Before** 

```yaml
- name: Run pre-commit scripts XYZ
  run: npm run pre-commit-xyz

- name: Commit Updates XYZ
  uses: EndBug/add-and-commit
  with:
    message: 'Update XYZ'
    add: '*'
```

**After** 

```yaml
- name: Update XYZ
  uses: EndBug/add-and-commit
  with:
    pre_commit: npm run pre-commit-xyz
    message: 'Update XYZ'
    add: '*'
```
