### ISSUE TITLE
Warning: There are environment variables missing from this runtime, but would be present on GitHub

### ISSUE THREAD

**Issue by justanotheranonymoususer** [EndBug/add-and-commit#516]
I'm not sure what I did wrong or maybe a bug. Also I can't share the project but let me know if you need more info, I believe the usage is rather standard.

```yaml
      - name: Commit
        uses: EndBug/add-and-commit@v9
        with:
          cwd: generated
          default_author: github_actions
          message: 'Update generated files'
          fetch: false
```

Output:
```
Run EndBug/add-and-commit@v9
  with:
    cwd: generated
    default_author: github_actions
    message Update generated files
    fetch: false
    add: .
    pathspec_error_handling: ignore
    push: true
    github_token: ***
Warning: There are environment variables missing from this runtime, but would be present on GitHub.
- HOME
```

![image](https://github.com/EndBug/add-and-commit/assets/5781692/e474c03c-10bc-47f0-8ecd-150ebb1451c9)
