### ISSUE TITLE
It doesn't work for me

### ISSUE THREAD

**Issue by razb-viola** [EndBug/add-and-commit#583]
No matter what I did, it just didn't create a new commit, either on the pushed branch or on new branch.

My repo is a repo under organization, but I checked the Read and Write permissions..

**Comment by razb-viola** [comment]
Sure here it is:

```
name: Tag and Release
on:
  push:
    branches:
      - main1
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4

      - name: Bump version and push tag
        id: tag_version
        uses: mathieudutour/github-tag-action@v6.1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          tag_prefix: ''

      - name: Echo the tag
        run: echo "Tag name ${{ steps.tag_version.outputs.new_tag }}"

      - name: Echo the changelog
        run: echo "Tag name ${{ steps.tag_version.outputs.changelog }}"

      - name: Echo package.json
        run: cat package.json

      - name: Configure node
        uses: actions/setup-node@v4
        with:
          node-version: '21.1.0'
          registry-url: 'https://registry.npmjs.org'

      - name: Tell who we are to npm
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "Github Actions"

      - name: Update package.json version
        run: npm version ${{ steps.tag_version.outputs.new_tag }}
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Echo package.json after update
        run: cat package.json

      - uses: EndBug/add-and-commit@v9

      - name: Publish to NPM registry
        run: npm publish --access=public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

```
