### ISSUE TITLE
Fetch only one branch for performance issues 

### ISSUE THREAD

**Issue by brandonfl** [EndBug/add-and-commit#597]
Hello, 

Since the fetch is taking a long time, I tryed to fetch only one branch with this configuration : 

```
env:
  BRANCH_REF: ${{ github.event.pull_request.head.ref || github.ref_name }}

...

- name: Push Changes
  uses: EndBug/add-and-commit@v9.1.3
  with:
    author_name: ...
    author_email: ...
    message: '...'
    fetch: origin ${{ env.BRANCH_REF }} --force
```

But this seems to still fetch all the repo, any idea ?

Thanks in advance,
Regards,
BrandonFL
