### ISSUE TITLE
Question: pull from main - push to otherbranch?

### ISSUE THREAD

**Issue by Stwissel** [EndBug/add-and-commit#63]
Use case:
I have a `front-end` (Angular/React) and a `backend` repository. When the CI is building the front-end, the result of the build folder needs to be committed to the `/static` directory of the backend repo. With your contribution I came close - love it.
The last hurdle is the error:

** Error: warning: Pulling without specifying how to reconcile divergent branches is discouraged **

which AFAIK stems from the fact that I checkout `master` from backend and try to push to (the non-existing) branch `ui-contribution`. Is there a way I can push to a new (or eventually existing) branch. `-u --force` might do the trick, but where to put in in the YAML. My stuff so far:

```yaml
name: Reconcile front and backend

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  buildui:
    name: Building UI
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Backend
        uses: actions/checkout@v2
        with:
          repository: acme/backend
          token: ${{secrets.UI_PUSH_TOKEN }}
          ref: main
          path: backend
      - name: Checkout UI
        uses: actions/checkout@v2
      - name: Deploy NodeJS
        uses: actions/setup-node@v1
        with:
          node-version: "12.x"
      - run: npm install
      - run: npm run build --if present
      - run: npm test
      - name: Send them back
        uses: EndBug/add-and-commit@v5
        with:
          cwd: "./backend"
          branch: "ui-commit"
          message: "[Auto-commit] from UI"
        env:
          GITHUB_TOKEN: ${{secrets.UI_PUSH_TOKEN }}

```

Love your work!
