### ISSUE TITLE
Error: fatal: Cannot prompt because user interactivity has been disabled.

### ISSUE THREAD

**Issue by andrewjswan** [EndBug/add-and-commit#633]
**Describe the bug**
Same issue as https://github.com/EndBug/add-and-commit/issues/146

**Workflow used**
```
      - name: Save cache
        if: "contains(github.event.head_commit.message, '[release]')"
        uses: actions/cache/save@v4
        with:
          path: ${{ github.workspace }}
          key: plugin-mpe

      - name: Git Checkout
        if: "contains(github.event.head_commit.message, '[release]')"
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Restore cache
        if: "contains(github.event.head_commit.message, '[release]')"
        uses: actions/cache/restore@v4
        with:
          path: ${{ github.workspace }}
          key: plugin-mpe

      - name: Update / MPE1 XML
        if: "contains(github.event.head_commit.message, '[release]')"
        uses: EndBug/add-and-commit@v9
        with:
          message: 'Update / MPE1 XML for ${{ steps.version.outputs.version }}'
          add: '${{ github.workspace }}\scripts\MyVideoImporter.xml'
```

**Expected behavior**
Commit one file 

**Logs**
https://github.com/andrewjswan/mediaportal-myvideo-importer/actions/runs/8332401020/job/22801697187
<details>
  <summary>Logs</summary>
<pre><code>Error: Error: fatal: Cannot prompt because user interactivity has been disabled.
bash: line 1: /dev/tty: No such device or address
error: failed to execute prompt script (exit code 1)
fatal: could not read Username for 'https://github.com/': No such file or directory</code></pre>
</details>
