### ISSUE TITLE
Fails without an error message

### ISSUE THREAD

**Issue by johnboiles** [EndBug/add-and-commit#640]
**Describe the bug**
Not sure why, but for some reason recently EndBug/add-and-commit has started to fail when trying to make the commit. It had been working fine for me for 1-2 years up until a month or two ago. It fails without a useful error message:

```
Add input parsed as single string, running 1 git add command.
> Using 'Clang Robot <robot@example.com>' as author.
> Using "Committing clang-format/clang-tidy changes" as commit message.
Internal logs
  > Staging files...
  > Adding files...
  > No files to remove.
  > Checking for uncommitted changes in the git working tree...
  > Found 1 changed files.
  > Fetching repo...
  Error: Error: From https://github.com/[ORGNAME]/[REPONAME]
   * [new branch]      [BRANCHNAME]          -> origin/[BRANCHNAME]
  ... repeats for other branches until the end of the log...
```

**Workflow used**
```
name: Run Clang Tools

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  clangify:
    runs-on:
      group: Beefy
    container:
      image: espressif/idf:v5.1

    steps:
      - uses: actions/checkout@v3
        with:
          repository: ${{ github.event.pull_request.head.repo.full_name }}
          ref: ${{ github.event.pull_request.head.ref }}
          submodules: "recursive"

      - name: Install tools
        run: |
          . $IDF_PATH/export.sh
          idf_tools.py install esp-clang
          pip install --upgrade pyclang

      # See https://github.com/actions/checkout/issues/1169
      - run: git config --system --add safe.directory /__w/embedded-app/embedded-app
        if: github.event_name == 'pull_request'

      - name: Run clang-tidy
        run: |
          . $IDF_PATH/export.sh
          IDF_TOOLCHAIN=clang idf.py -B build-clang clang-check --run-clang-tidy-py scripts/run-clang-tidy.py --run-clang-tidy-options "-fix -header-filter=embedded-app/src/.*" --exclude-paths managed_components --exclude-paths components

      - uses: DoozyX/clang-format-lint-action@v0.16.2
        with:
          source: "./src"
          extensions: "hpp,h,cpp,c"
          clangFormatVersion: 15
          inplace: True

      - uses: EndBug/add-and-commit@v9
        with:
          author_name: Clang Robot
          author_email: robot@example.com
          message: "Committing clang-format/clang-tidy changes"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        if: github.event_name == 'pull_request'
```

Seems like there's a good chance it's something related to running inside the Docker container possibly, but like I said it stopped working in the last month or so (and we had not changed the workflow since November '23). How do I debug this?
