### ISSUE TITLE
Permissions required for token. "Write access to repository not granted."

### ISSUE THREAD

**Issue by Foywards** [EndBug/add-and-commit#643]
Hello, this is probably a silly/noob question, but I'm struggling to get this step to work in a workflow.

![ObsidianGitBookSyncError](https://github.com/EndBug/add-and-commit/assets/171736314/eb36146e-996d-474e-b25b-973a55e40697)

The workflow definition file is below. I got this from the following repo: https://github.com/CommitSans/obsidian-gitbook

I have two private repos, one is a fork of the above, and the other is a repo containing a basic [Obsidian](https://obsidian.md/) Vault.

I have added the DEPLOY_PAT secret to both repos. (Essentially, the way it works is when the Obsidian repo gets a push, it calls this workflow to then convert the Obsidian Vault to a GitBook format.

```
name: Build GitBook
on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      repo:
        description: 'Repository to use as Obsidian project'
        type: string

jobs:
  run:
    name: Convert Obsidian to GitBook
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Print repo variable
        run: echo Repo variable is ${{ github.event.inputs.repo }}

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20.x

      - name: Clone Obsidian vault
        if: github.event.inputs.repo != null
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.DEPLOY_PAT }}
          repository: ${{github.event.inputs.repo}}
          path: obsidian

      - name: Install dependencies
        working-directory: ./src
        run: npm install

      - name: Run the builder
        working-directory: ./src
        run: npm run build:gitbook

      - name: Commit changes
        uses: EndBug/add-and-commit@v9
        with:
          message: '🤖 Build for GitBook'
          add: 'gitbook'
```

Anyhow, I'm probably just missing something obvious. I've tried switching between the PAT and GITHUB_TOKEN and that did not help. I switched from a fine-grained PAT to a classic PAT with the following permissions:
![GitHubPATpermissions](https://github.com/EndBug/add-and-commit/assets/171736314/4d6e4dc1-4b76-4f1b-be58-d2afb0dd6667)

Any ideas? Thanks so much in advance! :)
