### ISSUE TITLE
How to add current datetime in commit message?

### ISSUE THREAD

**Issue by hero** [EndBug/add-and-commit#648]
Just like I did in my bash shell:
```
git commit -m "Updated at `date '+%Y-%m-%d %H:%M:%S'`⚡️"
```

But I've tried, `add-and-commit@v9.1.4` commit the orignal strings, which was NOT I want.

**Comment by hero** [comment]
Okay, I solved this problem myself, the Github Actions command is as follows:
```   
- name: Get the current date time
  id: datetime
  run: echo "time_now=$(date '+%Y-%m-%d %H:%M:%S')" >> $GITHUB_OUTPUT

- name: Add & Commit
  uses: EndBug/add-and-commit@v9.1.4
  with:          
      message: "Updated at ${{ steps.datetime.outputs.time_now}} ⚡️"
```
