### ISSUE TITLE
Action creates a .netrc file in home directory

### ISSUE THREAD

**Issue by javierggt** [EndBug/add-and-commit#66]
In my setup, I am using a runner on premises. This runner does a couple other things. I included this action on a workflow I sent to that runner, and a side effect of the action is a .netrc file in the home directory of the user running the github runner (**overwriting** a previous .netrc in the same place). The action configuration is nothing special:
```
      - name: Commit changes
        uses: EndBug/add-and-commit@v4
        with:
          ref: "test"
          cwd: "test"
          author_name: <my name>
          author_email: <my email>
          message: "Save"
          add: "docs"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
```

The `test` directory contains the `test` branch of the repository, and was checked out using Github's actions/checkout.

To convince myself that this action was responsible, I tried with a few different values for GITHUB_TOKEN (setting it to other valid github tokens in my secrets list). That token always ended up in the .netrc file. Needless to say, this behavior is a deal breaker.

I don't know what more information to give you. You can replicate it by using this on your own runner, and checking that a .netrc is created.
