### ISSUE TITLE
Using `persist-credentials: false` leads to `could not read Username for 'https://github.com': No such device or address`

### ISSUE THREAD

**Issue by icemac** [EndBug/add-and-commit#673]
**Describe the bug**
Using `persist-credentials: false` in a private repository for `actions/checkout@v4` as suggested by https://github.com/woodruffw/zizmor leads to `could not read Username for 'https://github.com/': No such device or address`

**Workflow used**
```yaml
      - uses: actions/checkout@v4
        with:
          repository: ${{ github.event.pull_request.head.repo.full_name }}
          ref: ${{ github.event.pull_request.head.ref }}
          token: ${{ secrets.COMMIT_ACTIONS_TOKEN }}
...
      - name: Commit changes
        uses: EndBug/add-and-commit@v9
        with:
          committer_name: GitHub Actions
          committer_email: actions@github.com
          message: Version synchronisation
          add: '["toolkit/deps.cfg", "dependabot/requirements.txt"]'
```

**Expected behavior**
The documentation suggests to update to `actions/checkout@v2` for the error message I saw.
Maybe this just needs to be added to the documentation as another source for this error.

**Logs**
<details>
  <summary>Run EndBug/add-and-commit@v9</summary>
<pre><code>
Running in /home/runner/work/...
Add input parsed as string array, running 2 git add commands.
> Using 'dependabot[bot] <dependabot[bot]@users.noreply.github.com>' as author.
> Using custom committer info: GitHub Actions <actions@github.com>
> Using "Version synchronisation" as commit message.
> Internal logs
  > Staging files...
  > Adding files...
  > No files to remove.
  > Checking for uncommitted changes in the git working tree...
  > Found 1 changed files.
  > Fetching repo...
  Error: Error: fatal: could not read Username for 'https://github.com/': No such device or address
</code></pre>
</details>
