### ISSUE TITLE
could not read Username for 'https://github.com': No such device or address

### ISSUE THREAD

**Issue by steled** [EndBug/add-and-commit#675]
Hi,

I'm trying to use your action as a separate job within my `actions.yml` file.
So I have a separate job where I'm doing the checkout:

```yaml
jobs:

  repo_setup:
    runs-on: self-hosted

      - name: Checkout code
        uses: actions/checkout@v4.2.2
        with:
          ref: ${{ inputs.branch }}
          submodules: true
```

and than want to do your push in a separate/last job:

```yaml
  git_push:
    if: ${{ always() }}
    needs: [
      deployment_seed_fra_cluster,
      destruction
    ]
    runs-on: self-hosted
    steps:
      - name: git push
        uses: EndBug/add-and-commit@v9
        with:
          message: Pushing updated environment
          committer_name: username
          committer_email: username@mail
        env:
          GITHUB_TOKEN: ${{ secrets.KKP_PIPELINE }}
          GIT_AUTHOR_NAME: username
          GIT_AUTHOR_EMAIL: username@mail
          GITHUB_USER: username
```

As you can see I also tried it with different `env` values but always get:

`Error: Error: fatal: could not read Username for 'https://github.com/': No such device or address`.

How can I solve this problem?

Edit: As an additional information, I'm using it in a private repository.

**Comment by EndBug** [comment]
Each job happens in an isolated environment: local changes you make in one job do not persist in later ones, even if you specified them as dependencies.
You need to either run the action on that same job, or package and restore your changes using artifacts.

**Comment by steled** [comment]
As I am running on a self-hosted runner the code changes are persisted through the jobs.
But how can I configure your action to use a specific/different author?

**Comment by EndBug** [comment]
Oh, sorry, I hadn't noticed
Well, if you want to change the author you can use `author_name` and `author_email`

But the error you're getting is usually caused by incorrect or missing git credentials.
You would usually need to either persist the credentials form `actions/checkout` for the action to be able to push to the repo. 

The error could also be caused by a incorrect or missing GH token. Is your self-hosted runner providing `github.token`?
You can also override it by providing the `github_token` input.

https://github.com/EndBug/add-and-commit/blob/2afad56181d84749b0d88d950978f238c741f9c9/action.yml#L64-L67

**Comment by steled** [comment]
Ok, I could solve the problem by using the following step before your action:

```yaml
      - name: Set up git remote url
        run: |
          git remote set-url origin https://${{ secrets.REPO_PAT }}@github.com/username/repository.git
```
