### ISSUE TITLE
Support collections as values for `add`, `rm` and so on

### ISSUE THREAD

**Issue by trallnag** [EndBug/add-and-commit#95]
Hello, I think it would improve usability if we could use multiple `git add` commands with within a single action. For example:

```yml
- name: Commit changes
      uses: EndBug/add-and-commit@v5
      with:
        author_name: Your Name
        author_email: mail@example.com
        message: "Your commit message"
        add:
            - "something/file.txt"
            - "crazy/*"
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
```

This wouldn't even be a breaking change if both collections and scalars are supported.

At the moment it is possible to to it like this `git add file-1 file-2 file-3`, which translates to `add: file-1 file-2 file-3`, but what if the  path has a space in it?
